language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
before_install:
  - echo 'hhvm.libxml.ext_entity_whitelist = file,http,https' > travis.hhvm.ini
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then hhvm -c travis.hhvm.ini $HOME/.phpenv/versions/hhv/bin/phpunit; fi;'
